name: Benchmark
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - ".github/**"
      - "klv/**"
jobs:
  build_cache:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v3
      - &apt-cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - &rust-cache
        uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - name: build
        run: cargo build
  bench_klv:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - *checkout
      - *apt-cache
      - *rust-cache
      - name: bench
        run: cargo bench --all
