---
name: Benchmark
"on":
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/**"
      - klv/**
    branches:
      - master
jobs:
  build_cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - name: build
        run: cargo build
  bench_klv:
    runs-on: ubuntu-20.04
    needs: build_cache
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - uses: Swatinem/rust-cache@v2
      - name: bench
        run: cargo bench --all