---
name: Build and test
"on":
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/**"
      - klv/**
jobs:
  build_cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - name: build
        run: cargo build
      - name: check format
        run: cargo fmt --all -- --check
      - name: check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo test --all -- --nocapture
